descriptor-schema-version: "2.7"
info:
  name: gve_devnet/iox_iperf_app
  version: "2.2"
  description: "IOx Docker Iperf app"
  author-link: "https://github.com/gve-sw"
  author-name: "Cisco GVE DevNet"
app:
  cpuarch: x86_64
  env:
    PATH: /usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
  resources:
    network:
    - interface-name: eth0
      ports:
        tcp:
        - "5500"
    profile: c1.small
  startup:
    rootfs: rootfs.tar
    target:
    - gunicorn
    - -b 0.0.0.0:5500
    - app:app
    - --log-file ${CAF_APP_LOG_DIR}/webapp.log
    - --log-level debug
    workdir: /app/
  type: docker